version: "3.8"

services:
  harjoitus23front:
    image: frontjyva
    build: .
    ports:
      - 127.0.0.1:5000:5000
    container_name: 26front
    command: ["serve", "-s", "-l", "5000", "build"]
  harjoitus23back:
    image: backejyva
    build: .
    ports:
      - 127.0.0.1:8080:8080
    container_name: 26back
#    command: [ "server"]
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=26redis
      - POSTGRES_HOST=26postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  redisServer:
    image: redis
    container_name: 26redis
  postgresServer:
    image: postgres
    container_name: 26postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
